### GET ALL BLOGS
GET http://localhost:3003/api/blogs


### GET ALL USERS
GET http://localhost:3003/api/users


### ADD BLOG
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVsb24iLCJpZCI6IjYzMjIxY2E3ODNhYTg3MzhmZWVkYmQ4OSIsImlhdCI6MTY2MzE4OTQxMSwiZXhwIjoxNjYzMTkzMDExfQ.VoTpRX6x_mMA52YY-nTQnWxIIKatlTmHl5Cu1zq5m_0

{
  "title": "ada1fweew asd",
  "author": "elon",
  "likes": 2,
  "url": "https://apple.com/uk/"
}


### DELETE BLOG
DELETE http://localhost:3003/api/blogs/631a24a5c509d2376d6599df
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzMTkzMWQ3NzQ4NWYwMmZlYTMxNmZlNCIsImlhdCI6MTY2MjY1NDY4MSwiZXhwIjoxNjYyNjU4MjgxfQ.HuueU0KtDeRbv3sjnwKmIIhVEtDd6XhvG9jch1R8Kao


### UPDATE BLOG
PUT http://localhost:3003/api/blogs/63221f2d83aa8738feedbdbb
Content-Type: application/json

{
  "title": "1234",
  "likes": 0
}


### LOGIN alexlime
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "alex",
    "password": "root"
}


### LOGIN 
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "elon",
    "password": "root"
}


### ADD USER
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "elon",
    "name": "Elon Musk",
    "password": "root"
}


### TESTING reset testing database
POST http://localhost:3003/api/testing/reset
